
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  port: 5432
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: product-register_development

test:
  <<: *default
  database: product-register_test

production:
  <<: *default
  database: product-register_production
  username: product-register
  password: <%= ENV['PRODUCT-REGISTER_DATABASE_PASSWORD'] %>
